# Generated by Django 5.1.2 on 2026-09-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0007_alter_farmparcel_geo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agriculturalmachine',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='compostmaterial',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='farm',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='farmanimal',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='farmcrop',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='farmparcel',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='farmsensor',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='genericfarmasset',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicalagriculturalmachine',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicalcompostmaterial',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicalfarm',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicalfarmanimal',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicalfarmcrop',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicalfarmparcel',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicalfarmsensor',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicalfertilizer',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicalgenericfarmasset',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='historicalpesticide',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
        migrations.AddField(
            model_name='pesticide',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
    ]
