# Generated by Django 5.1.2 on 2026-09-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management', '0008_agriculturalmachine_tenant_compostmaterial_tenant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmparcel',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='historicalfarmparcel',
            name='identifier',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='farmparcel',
            constraint=models.UniqueConstraint(fields=('tenant', 'identifier'), name='uniq_farmparcel_tenant_identifier'),
        ),
    ]
