# Generated by Django 5.1.2 on 2026-09-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_activities', '0016_animallactatingactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmcalendaractivity',
            name='tenant',
            field=models.CharField(blank=True, db_index=True, help_text='Referencia opaca al cliente propietario del registro.', max_length=64, null=True, verbose_name='Tenant'),
        ),
    ]
